version: "3.8"

volumes:
  mongo-volume-db:
  mongo-volume-configdb:

services:
  mongo:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./docker-compose/mongodb:/docker-entrypoint-initdb.d/
      - mongo-volume-db:/data/db
      - mongo-volume-configdb:/data/configdb
